### ISSUE TITLE
It would be good to have a system that offered 'data product' (i.e. with a temporal cut-off) and allowed users to visualise (and access) 'historic' data products as well.

### ISSUE THREAD

**Issue by jonparsonsjncc** [ices-tools-dev/cetaceans#129] opened 2020-12-03 14:56 UTC
yes but each time period will have its own data product

**Comment by LynnHeeley** [comment] 2021-01-15 13:56
duplicate of #133

**Closed** 2021-02-09 11:55 UTC
Labels: Objective: Data product, duplicate, rejected
