### ISSUE TITLE
As a data user I want to access the data products directly inside my GIS application, so that I can use them in my own analyses without having to download a copy

### ISSUE THREAD

**Issue by GMDuncan** [ices-tools-dev/cetaceans#193] opened 2020-12-10 11:49 UTC
duplicate of #102 , close ticket

**Comment by neil-ices-dk** [comment] 2021-01-08 08:40
@kellymacleod this sounds like a standard WMS/WFS service; if the issue is on data access, then we have to agree - like for all ICES data products, that they are publically available without impediment (i.e. aggregated/anonymized etc.) to a degree that protects the data provider in terms of identifying sensitive areas etc. 

We therefore don't see this as a big ticket

**Comment by LynnHeeley** [comment] 2021-01-27 16:41
@neil-ices-dk is it just the publically available data that is included in the WFS/WMS (ie not the restricted data)? and your second point - if the data is marked as sensitive that is also not included in the service?

**Comment by neil-ices-dk** [comment] 2021-01-27 20:04
@LynnHeeley the WFS/WMS would include public AND restricted data but sufficiently aggregated to avoid that one could extract the original restricted data in its detailed form i.e. gridding the data to a spatial resolution that is lower (f.ex 10 x 10 km) than the original restricted data (f.ex 1 x 1 km).

**Closed** 2021-02-12 19:10 UTC
Labels: In the ICES bag, category: data products, data user, duplicate, theme: access, theme: analytics, theme: download
