### ISSUE TITLE
As a Data user I want to be able to select a standard region to investigate so that I have options to easily extract data from the system / analyse data

### ISSUE THREAD

**Issue by GMDuncan** [ices-tools-dev/cetaceans#162] opened 2020-12-09 14:27 UTC
Split from #104  to separate geospatial selections

Standard regions will come from a predetermined list (to be determined, but likely OSPAR and/or MSFD)

@neil-ices-dk 'in the ICES bag'?

**Comment by neil-ices-dk** [comment] 2021-02-11 13:48
Bagged 🛄

**Comment by LynnHeeley** [comment] 2021-03-29 15:30
duplicate of #62

**Closed by LynnHeeley** 2021-03-29 15:30 UTC
Labels: In the ICES bag, MVP, category: data products, category: system, data user, theme: download
