### ISSUE TITLE
As a Partner I want to understand the outputs that the data facilitates so that I can demonstrate value of the portal (eg tracking DOIs)

### ISSUE THREAD

**Issue by pcrjoana** [ices-tools-dev/cetaceans#170] opened 2020-12-10 09:47 UTC
#98

**Comment by neil-ices-dk** [comment] 2021-01-08 09:32
@kellymacleod duplicate of #98 suggest to reject this issue in favour of the other

**Closed** 2021-02-10 20:31 UTC
Labels: Objective: Data product, category: system, duplicate, partner, rejected
