### ISSUE TITLE
As a Data user I want to have access to datasets of species distribution ..so that I can include this (referenced, as required) in my work #57 NOT A PRODUCT

### ISSUE THREAD

**Issue by GMDuncan** [ices-tools-dev/cetaceans#184] opened 2020-12-10 11:18 UTC
True data here rather than visualisation map (#57 
This is about access to data and visualisation of a map of sightings

**Comment by LynnHeeley** [comment] 2021-03-17 19:51
duplicate of #54 close

**Closed by LynnHeeley** 2021-03-17 19:51 UTC
Labels: MVP, category: data products, data user, theme: download
